/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import {
  Navbar,
} from '../client/components/Navbar';
import { QuestionForm } from '../client/components/QuestionForm';
import { AnswerCard } from '../client/components/AnswerCard';
import { HistoryList } from '../client/components/HistoryList';
import { ArchitectureDiagram } from '../client/components/ArchitectureDiagram';
import { DocsView } from '../client/components/DocsView';
import {
  askStudyQuestion,
  getStudyHistory,
  deleteStudyItem,
  getStudyBackendInfo,
  StudyItem,
} from '../client/services/api';
import {
  GraduationCap,
  Sparkles,
  Layers,
  FileText,
  AlertTriangle,
  RefreshCw,
} from 'lucide-react';

export default function App() {
  const [currentTab, setCurrentTab] = useState<'home' | 'history' | 'architecture' | 'docs'>('home');
  const [latestAnswer, setLatestAnswer] = useState<StudyItem | null>(null);
  const [history, setHistory] = useState<StudyItem[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [initialLoading, setInitialLoading] = useState<boolean>(true);
  const [storageInfo, setStorageInfo] = useState<any>(null);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  // Load history & storage metadata on mount
  useEffect(() => {
    loadInitialData();
  }, []);

  const loadInitialData = async () => {
    try {
      setInitialLoading(true);
      const historyData = await getStudyHistory();
      setHistory(historyData.items);
      if (historyData.storage) {
        setStorageInfo(historyData.storage);
      }

      // Also fetch backend info
      const info = await getStudyBackendInfo();
      if (info?.storage) {
        setStorageInfo(info.storage);
      }
    } catch (err) {
      console.warn('Initial data load warning:', err);
    } finally {
      setInitialLoading(false);
    }
  };

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => {
      setToastMessage(null);
    }, 4000);
  };

  const handleAskQuestion = async (subject: string, question: string) => {
    setIsLoading(true);
    try {
      const result = await askStudyQuestion(subject, question);
      setLatestAnswer(result);
      // Prepend newly saved MongoDB document to local history state
      setHistory((prev) => [result, ...prev]);
      showToast('Answer generated by Gemini and saved to MongoDB!');
    } finally {
      setIsLoading(false);
    }
  };

  const handleDeleteQuestion = async (id: string) => {
    await deleteStudyItem(id);
    setHistory((prev) => prev.filter((item) => item._id !== id));
    if (latestAnswer?._id === id) {
      setLatestAnswer(null);
    }
    showToast('Question deleted from MongoDB.');
  };

  return (
    <div className="min-vh-100 d-flex flex-column bg-light">
      {/* Bootstrap Navbar */}
      <Navbar
        currentTab={currentTab}
        setCurrentTab={setCurrentTab}
        historyCount={history.length}
        storageInfo={storageInfo}
      />

      {/* Toast notification banner */}
      {toastMessage && (
        <div
          className="alert alert-success alert-dismissible fade show position-fixed top-0 start-50 translate-middle-x mt-3 z-3 shadow"
          role="alert"
          style={{ minWidth: '320px' }}
        >
          <div className="d-flex align-items-center gap-2">
            <Sparkles size={16} className="text-success" />
            <span className="small fw-semibold">{toastMessage}</span>
          </div>
          <button
            type="button"
            className="btn-close py-2"
            onClick={() => setToastMessage(null)}
          ></button>
        </div>
      )}

      {/* Main Container */}
      <main className="container my-4 flex-grow-1">
        {/* Welcome Header */}
        <div className="p-4 mb-4 bg-white rounded-3 shadow-sm border">
          <div className="row align-items-center">
            <div className="col-lg-8">
              <div className="d-flex align-items-center gap-2 mb-2">
                <span className="badge bg-primary-subtle text-primary border border-primary-subtle">
                  CS Engineering Study Tool
                </span>
                <span className="badge bg-secondary-subtle text-secondary border border-secondary-subtle font-monospace">
                  REST API + MongoDB + Gemini
                </span>
              </div>
              <h2 className="fw-bold text-dark mb-1">
                College CS Study Assistant
              </h2>
              <p className="text-muted mb-0">
                Get crystal-clear explanations, practical code examples, and exam summaries for core computer science subjects.
              </p>
            </div>
            <div className="col-lg-4 text-lg-end mt-3 mt-lg-0">
              <div className="d-flex justify-content-lg-end gap-2">
                <button
                  className={`btn btn-sm ${currentTab === 'home' ? 'btn-primary' : 'btn-outline-secondary'}`}
                  onClick={() => setCurrentTab('home')}
                >
                  <Sparkles size={14} className="me-1" />
                  Ask Question
                </button>
                <button
                  className={`btn btn-sm ${currentTab === 'history' ? 'btn-primary' : 'btn-outline-secondary'}`}
                  onClick={() => setCurrentTab('history')}
                >
                  History ({history.length})
                </button>
                <button
                  className={`btn btn-sm ${currentTab === 'architecture' ? 'btn-primary' : 'btn-outline-secondary'}`}
                  onClick={() => setCurrentTab('architecture')}
                >
                  Flow
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Tab 1: Home (Form + Latest Answer) */}
        {currentTab === 'home' && (
          <div>
            <QuestionForm onSubmit={handleAskQuestion} isLoading={isLoading} />

            {/* Display Response if available */}
            {latestAnswer && (
              <div className="mt-4">
                <div className="d-flex justify-content-between align-items-center mb-2">
                  <h5 className="fw-bold text-dark mb-0">
                    Latest Answer (Saved in MongoDB)
                  </h5>
                  <button
                    className="btn btn-sm btn-link text-decoration-none"
                    onClick={() => setCurrentTab('history')}
                  >
                    View All in History →
                  </button>
                </div>
                <AnswerCard
                  item={latestAnswer}
                  onDelete={handleDeleteQuestion}
                  isNew={true}
                />
              </div>
            )}

            {/* Quick preview of recent questions if no latest answer yet */}
            {!latestAnswer && history.length > 0 && (
              <div className="card shadow-sm border-0 mt-4">
                <div className="card-header bg-white py-3 d-flex justify-content-between align-items-center">
                  <h6 className="fw-bold mb-0 text-dark">
                    Recently Asked Questions ({Math.min(3, history.length)})
                  </h6>
                  <button
                    className="btn btn-sm btn-outline-primary"
                    onClick={() => setCurrentTab('history')}
                  >
                    Open Full History ({history.length})
                  </button>
                </div>
                <div className="card-body p-0">
                  <div className="list-group list-group-flush">
                    {history.slice(0, 3).map((item) => (
                      <div
                        key={item._id}
                        className="list-group-item list-group-item-action p-3"
                      >
                        <div className="d-flex w-100 justify-content-between align-items-center mb-1">
                          <span className="badge bg-secondary me-2">
                            {item.subject}
                          </span>
                          <small className="text-muted">
                            {new Date(item.createdAt).toLocaleDateString()}
                          </small>
                        </div>
                        <h6 className="mb-1 text-dark fw-semibold">
                          {item.question}
                        </h6>
                        <p className="mb-1 text-muted small text-truncate">
                          {item.summary}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Tab 2: History Page */}
        {currentTab === 'history' && (
          <HistoryList
            items={history}
            onDelete={handleDeleteQuestion}
            onNavigateHome={() => setCurrentTab('home')}
            isLoading={initialLoading}
          />
        )}

        {/* Tab 3: Full-Stack Architecture Diagram */}
        {currentTab === 'architecture' && <ArchitectureDiagram />}

        {/* Tab 4: API Docs & MongoDB Schema */}
        {currentTab === 'docs' && <DocsView />}
      </main>

      {/* College Student Project Footer */}
      <footer className="bg-white border-top py-3 mt-auto text-center text-muted small">
        <div className="container d-flex flex-column flex-sm-row justify-content-between align-items-center gap-2">
          <div>
            <strong>AI Study Assistant</strong> &bull; Built with React, Bootstrap, Node.js, Express, MongoDB & Gemini LLM
          </div>
          <div className="d-flex gap-3">
            <button
              className="btn btn-link btn-sm text-secondary p-0 text-decoration-none"
              onClick={() => setCurrentTab('architecture')}
            >
              How It Works
            </button>
            <button
              className="btn btn-link btn-sm text-secondary p-0 text-decoration-none"
              onClick={() => setCurrentTab('docs')}
            >
              API Docs
            </button>
          </div>
        </div>
      </footer>
    </div>
  );
}
